Repository graasp/graasp-apps-query-client, pull requests merged in 2023-11, with the labels that each got.

#196 feat: add mobile context communication
  src/components/withContext.tsx
  src/hooks/postMessage.ts
  src/types.ts
  test/constants.ts
Labels: feature

#207 fix: pass mock context when resetting the DB
  .gitignore
  src/mockServer/msw/handlers.ts
Labels: bug :beetle:

#210 feat: ensure to store array in setQueryData of post data and setting
  src/mutations/appData.ts
  src/mutations/appSetting.ts
Labels: improvement

#199 fix: update chatbot to be a query-client
  .gitignore
  src/api/chatBot.ts
  src/api/index.ts
  src/hooks/index.ts
  src/hooks/useChatbotApi.tsx
  src/mutations/appAction.ts
  src/mutations/chatBot.ts
  src/mutations/index.ts
  src/routines/chatBot.ts
  src/routines/index.ts
  src/types.ts
Labels: improvement
