Repository graasp/graasp-apps-query-client, pull requests merged in 2023-08, with the labels that each got.

#145 fix: improve notifier type
  package.json
  src/hooks/postMessage.ts
  src/types.ts
  yarn.lock
Labels: chore

#161 fix(hooks): default values
  src/hooks/appAction.ts
  src/hooks/appData.ts
  src/hooks/appSetting.ts
Labels: bug :beetle:

#163 fix: remove usage of process.env
  package.json
  src/queryClient.ts
  yarn.lock
Labels: bug :beetle:, chore
