Repository graasp/graasp-apps-query-client, pull requests merged in 2024-09, with the labels that each got.

#398 fix: move sdk to peer dependency
  package.json
  yarn.lock
Labels: chore, dependencies

#402 feat: build with typescript
  eslint.config.mjs
  package.json
  package.tgz
  src/api/appAction.ts
  src/api/appData.ts
  src/api/appSetting.ts
  src/api/apps.ts
  src/api/chatBot.ts
  src/api/index.ts
  src/api/mocks.ts
  src/components/GraaspContextDevTool.tsx
  src/components/index.ts
  src/components/utils/hooks.ts
  src/components/withContext.tsx
  src/components/withToken.tsx
  src/config/utils.ts
  src/hooks/app.test.ts
  src/hooks/app.ts
  src/hooks/appAction.ts
  src/hooks/appData.test.ts
  src/hooks/appData.ts
  src/hooks/appSetting.test.ts
  src/hooks/appSetting.ts
  src/hooks/index.ts
  src/hooks/postMessage.test.ts
  src/hooks/postMessage.ts
  src/index.ts
  src/mockServer/fixtures.ts
  src/mockServer/mirage/server.ts
  src/mockServer/mockServer.ts
  src/mockServer/msw/dexie-db.ts
  src/mockServer/msw/handlers.ts
  src/mockServer/msw/server.ts
  src/mutations/appAction.ts
  src/mutations/appData.test.ts
  src/mutations/appData.ts
  src/mutations/appSetting.test.ts
  src/mutations/appSetting.ts
  src/mutations/chatBot.ts
  src/mutations/index.ts
  src/queryClient.ts
  src/routines/appAction.ts
  src/routines/appData.ts
  src/routines/appSetting.ts
  src/routines/chatBot.ts
  src/routines/index.ts
  src/routines/postMessage.ts
  src/utils/chatbot.ts
  src/utils/index.ts
  src/window.ts
  src/ws/hooks/app.test.ts
  src/ws/hooks/app.ts
  src/ws/hooks/index.ts
  src/ws/index.ts
  src/ws/ws-client.ts
  test/utils.tsx
  test/wsUtils.tsx
  tsconfig.build.json
  tsconfig.json
Labels: chore, feature

#413 build: fix lockfile
  yarn.lock
Labels: bug :beetle:, build
