Repository graasp/graasp-apps-query-client, pull requests merged in 2024-02, with the labels that each got.

#261 fix: allow reload of document
  src/components/withContext.tsx
Labels: bug :beetle:

#264 fix(ws): insert data without duplication
  src/ws/hooks/app.test.ts
  src/ws/hooks/app.ts
Labels: bug :beetle:, priority

#278 Graasp SDK 4.x
  commitlint.config.ts
  package.json
  src/components/GraaspContextDevTool.tsx
  test/utils.tsx
  tsconfig.eslint.json
  yarn.lock
Labels: bug :beetle:, dependencies
